import AccountBalanceWalletIcon from "@mui/icons-material/AccountBalanceWallet";
import MapsHomeWorkRoundedIcon from "@mui/icons-material/MapsHomeWorkRounded";
import { green, red } from "@mui/material/colors";

const columns = [
  {
    id: "uniqueID",
    label: "ID.",
    // minWidth: 70,
    align: "center",
    // backgroundColor: red[900],
  },
  { id: "lesseeBranchType", label: "Type", minWidth: 70, align: "center" },
  {
    id: "agreementActivationStatus",
    label: "Activation Status",
    // minWidth:120,
    align: "center",
  },
  { id: "branchID", label: "Offical ID", align: "center" },
  {
    id: "lesseeBranchName",
    label: "Office Name",
    minWidth: 70,
    align: "center",
  },
  // { id: "lesseeAreaName", label: "Area", minWidth: 70, align: "center" },
  { id: "premesisDistrict", label: "District", minWidth: 70, align: "center" },
  { id: "lesseeDivision", label: "RO Name", minWidth: 70, align: "center" },
  { id: "lesseeState", label: "State", minWidth: 70, align: "center" },
  { id: "lessorName", label: "Lesssor Name", minWidth: 70, align: "center" },
  {
    id: "lessorContactNumber",
    label: "Contact No.",
    minWidth: 70,
    align: "center",
  },

  // { id: "col11", label: "Bank Name", minWidth: 70, align: "center" },
  // { id: "col12", label: "IFSC Code.", minWidth: 70, align: "center" },
  // { id: "col13", label: "Account No", minWidth: 70, align: "center" },
  // { id: "col14", label: "Remitting Bank", minWidth: 70, align: "center" },
  // {
  //   id: "agreementSignDate",
  //   label: "Agreement Sign Date",
  //   minWidth: 70,
  //   align: "center",
  // },
  // {
  //   id: "agreementTenure",
  //   label: "Terms [months]",
  //   minWidth: 70,
  //   align: "center",
  // },
  // {
  //   id: "col17",
  //   label: "Agreement Start Date",
  //   minWidth: 70,
  //   align: "center",
  // },
  // {
  //   id: "agreementEndDate",
  //   label: "Agreement End Date",
  //   minWidth: 70,
  //   align: "center",
  // },
  // { id: "col19", label: "Rent Start Date", minWidth: 70, align: "center" },
  // { id: "col20", label: "Rent End Date", minWidth: 70, align: "center" },
  {
    id: "securityDepositAmount",
    label: "Security Deposit (Rs.)",
    minWidth: 70,
    align: "center",
  },
  {
    id: "monthlyRent",
    label: "Monthly Rent (Rs.)",
    minWidth: 70,
    align: "center",
  },
  // { id: "col23", label: "TDS(%)", minWidth: 70, align: "center" },
  // {
  //   id: "col24",
  //   label: "First Month Value (Rs.)",
  //   minWidth: 70,
  //   align: "center",
  // },
  // {
  //   id: "col25",
  //   label: "Last Month Value (Rs.)",
  //   minWidth: 70,
  //   align: "center",
  // },
  // { id: "col26", label: "First Rent Date", minWidth: 70, align: "center" },
  // { id: "col27", label: "Last Rent Date", minWidth: 70, align: "center" },
  // { id: "col28", label: "Standard Deduction", minWidth: 70, align: "center" },
  // { id: "col29", label: "Renewal (%)", minWidth: 70, align: "center" },
  // { id: "col30", label: "Settlement Value", minWidth: 70, align: "center" },
  // { id: "col31", label: "Settlement Date", minWidth: 70, align: "center" },

  // {
  //   id: "remainingDays",
  //   label: "Remaining Days for Renewals",
  //   minWidth: 70,
  //   align: "center",
  // },

  // {
  //   id: "renewalStatus",
  //   label: "Renewal / Relocation Status",
  //   minWidth: 70,
  //   align: "center",
  // },
  {
    id: "edit",
    label: "",
    minWidth: 10,
    icon: null,
    actions: ["edit"],
    align: "center",
    display: "flex",
    flexDirection: "row",
    modalIcon: "",
  },
  {
    id: "viewBank",
    label: "",
    minWidth: -10,

    icon: null,
    actions: ["viewBank"],
    align: "center",
    display: "flex",
    flexDirection: "row",
    modalIcon: "",
  },
  {
    id: "viewBranch",
    label: "Actions",
    minWidth: -10,
    align: "center",
    icon: null,
    actions: ["viewBranch"],
  },
  {
    id: "viewAgreement",
    label: "",
    minWidth: -10,
    align: "center",
    icon: null,
    actions: ["viewAgreement"],
  },
  // {
  //   id: "viewUploadedAgreement",
  //   label: "",
  //   minWidth: 70,
  //   align: "center",
  //   icon: null,
  //   actions: ["viewUploadedAgreement"],
  // },
];
export { columns };
